-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/pagelike_like (
  pll_page_id INT UNSIGNED NOT NULL,
  pll_user_id INT UNSIGNED NOT NULL,
  pll_liked_at BINARY(14) NOT NULL,
  INDEX pagelike_like_liked_at_page (pll_liked_at, pll_page_id),
  INDEX pagelike_like_user_page (pll_user_id, pll_page_id),
  PRIMARY KEY(pll_page_id, pll_user_id)
) /*$wgDBTableOptions*/;
